#!/usr/bin/env python
import pygrib, sys
if len(sys.argv) < 2:
    print "'grib_list <grib_filename>' to get long listing"
    print "'grib_list <grib_filename> -s' to get short listing"
    sys.exit(1)
fname = sys.argv[1]
short = False
if len(sys.argv) > 2 and sys.argv[2] == '-s':
    short = True
grbs = pygrib.open(fname)
if short:
    for grb in grbs:
        print grb
else:
    for grb in grbs:
        print '------message %d------' %grb.messagenumber
        for k in grb.keys():
            if k.startswith('mars'): continue
            if k == 'values' or k == 'codedValues': continue
            if type(grb[k]) == int and grb[k] == grb.missingvalue_long:
                print k,'= MISSING'
            elif type(grb[k]) == float and grb[k] == grb.missingvalue_double:
                print k,'= MISSING'
            else:
                print k,'=',grb[k]
        data = grb['values']
        print 'min/max of data = ',data.min(),data.max()
grbs.close()
